# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tags_vocabulary.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'tags_vocabulary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15tags_vocabulary.proto\x12\x10\x63urator.protobuf\")\n\x0bTranslation\x12\x0c\n\x04lang\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x8d\x01\n\x03Tag\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x14\n\x0csub_category\x18\x05 \x01(\t\x12\x33\n\x0ctranslations\x18\x06 \x03(\x0b\x32\x1d.curator.protobuf.Translation\"{\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tavailable\x18\x03 \x01(\x08\x12\r\n\x05order\x18\x04 \x01(\x05\x12\x33\n\x0ctranslations\x18\x05 \x03(\x0b\x32\x1d.curator.protobuf.Translation\"\xa0\x01\n\rTagVocabulary\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x15\n\rmodified_time\x18\x02 \x01(\t\x12\x12\n\nvocab_size\x18\x03 \x01(\x05\x12#\n\x04tags\x18\x04 \x03(\x0b\x32\x15.curator.protobuf.Tag\x12.\n\ncategories\x18\x05 \x03(\x0b\x32\x1a.curator.protobuf.Categoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tags_vocabulary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATION']._serialized_start=43
  _globals['_TRANSLATION']._serialized_end=84
  _globals['_TAG']._serialized_start=87
  _globals['_TAG']._serialized_end=228
  _globals['_CATEGORY']._serialized_start=230
  _globals['_CATEGORY']._serialized_end=353
  _globals['_TAGVOCABULARY']._serialized_start=356
  _globals['_TAGVOCABULARY']._serialized_end=516
# @@protoc_insertion_point(module_scope)
