name: "Bug Report"
description: "报告缺陷或异常行为"
labels: ["type:bug"]

body:
  - type: textarea
    id: problem
    attributes:
      label: 问题
      placeholder: 发生了什么？
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      placeholder: 怎样触发这个问题？

  - type: textarea
    id: expected
    attributes:
      label: 期望行为
      placeholder: 正确的表现应该是什么？
