name: "Feature Request"
description: "提出新功能需求"
labels: ["type:feature"]

body:
  - type: textarea
    id: background
    attributes:
      label: 背景
      placeholder: 为什么需要这个功能？
    validations:
      required: true

  - type: textarea
    id: requirement
    attributes:
      label: 需求
      placeholder: 具体的功能描述和交互流程

  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准
      placeholder: 怎样算做完了？
