name: "Feature Request"
description: "提出新功能需求"
labels: ["type:feature"]

body:
  - type: markdown
    attributes:
      value: |
        ### 请描述你的需求，建议包含以下信息:
        - **背景**: 为什么需要这个功能？
        - **需求**: 具体的功能描述和交互流程
        - **验收标准**: 怎样算做完了？

  - type: textarea
    id: description
    attributes:
      label: 需求描述
    validations:
      required: true
