name: "Refactor"
description: "提出代码重构需求"
labels: ["type:refactor"]

body:
  - type: textarea
    id: goal
    attributes:
      label: 目标
      placeholder: 重构想达到什么效果？
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 动机
      placeholder: 当前代码存在什么问题？

  - type: textarea
    id: scope
    attributes:
      label: 范围
      placeholder: 涉及哪些文件或模块？
