name: "Refactor"
description: "提出代码重构需求"
labels: ["type:refactor"]

body:
  - type: markdown
    attributes:
      value: |
        ### 请描述重构需求，建议包含以下信息:
        - **目标**: 重构想达到什么效果？
        - **动机**: 当前代码存在什么问题？
        - **范围**: 涉及哪些文件或模块？

  - type: textarea
    id: description
    attributes:
      label: 重构描述
    validations:
      required: true
